### ISSUE TITLE
single option in #drilldownlink produces error

### ISSUE THREAD

**Issue by krabina** [SemanticMediaWiki/SemanticDrilldown#10]
Setting `{{#drilldownlink:category=foo|single}}` produces an error that does not show when the single option is omitted.

```
[6f2d34bbccc0b1d6716e849e] /Special:BrowseData/Die_Study?_single= Error from line 38 of /extensions/SemanticDrilldown/includes/Specials/BrowseData/ProcessTemplate.php: Unsupported operand types

Backtrace:

#0 extensions/SemanticDrilldown/includes/Specials/BrowseData/SpecialBrowseData.php(71): SD\Specials\BrowseData\ProcessTemplate->__invoke()
#1 /var/www/silver/1.35.8/includes/specialpage/SpecialPage.php(600): SD\Specials\BrowseData\SpecialBrowseData->execute()
#2 /var/www/silver/1.35.8/includes/specialpage/SpecialPageFactory.php(635): SpecialPage->run()
#3 /var/www/silver/1.35.8/includes/MediaWiki.php(307): MediaWiki\SpecialPage\SpecialPageFactory->executePath()
#4 /var/www/silver/1.35.8/includes/MediaWiki.php(947): MediaWiki->performRequest()
#5 /var/www/silver/1.35.8/includes/MediaWiki.php(547): MediaWiki->main()
#6 /var/www/silver/1.35.8/index.php(53): MediaWiki->run()
#7 /var/www/silver/1.35.8/index.php(46): wfIndexMain()
#8 {main}

```

**Comment by gesinn-it-gea** [comment]
`single` should hide the list of categories as described in https://www.mediawiki.org/wiki/Extension:Semantic_Drilldown#Linking_to_a_drilldown_page

**Comment by gesinn-it-gea** [comment]
should be covered by tests

**Comment by krabina** [comment]
Probably fixed by #72
