### ISSUE TITLE
Error: Class "PSExtensionHandler" not found

### ISSUE THREAD

**Issue by physikerwelt** [SemanticMediaWiki/SemanticDrilldown#59]
Steps to replicate the issue (include links if applicable):

    Install SMW 4.1.1 and Semantic drilldown
    run upate.php

What happens?:

I see the following error

Deprecated: Use of Hooks::run was deprecated in MediaWiki 1.35. [Called from SMW\MediaWiki\HookDispatcher::onSettingsBeforeInitializationComplete in /var/www/html/extensions/SemanticMediaWiki/src/MediaWiki/HookDispatcher.php at line 93] in /var/www/html/includes/debug/MWDebug.php on line 382
[d87d18b258193f44ecbd4a33] [no req]   Error: Class "PSExtensionHandler" not found
Backtrace:
from /var/www/html/extensions/SemanticDrilldown/includes/PageSchemas.php(15)
#0 /var/www/html/includes/AutoLoader.php(222): require()
#1 [internal function]: AutoLoader::autoload(string)
#2 /var/www/html/includes/HookContainer/HookContainer.php(344): is_callable(string)
#3 /var/www/html/includes/HookContainer/HookContainer.php(521): MediaWiki\HookContainer\HookContainer->normalizeHandler(string, string, array)
#4 /var/www/html/includes/HookContainer/HookContainer.php(450): MediaWiki\HookContainer\HookContainer->getHandlers(string)
#5 /var/www/html/extensions/SemanticMediaWiki/src/MediaWiki/Hooks.php(152): MediaWiki\HookContainer\HookContainer->register(string, array)
#6 /var/www/html/extensions/SemanticMediaWiki/src/Setup.php(389): SMW\MediaWiki\Hooks->register(array)
#7 /var/www/html/extensions/SemanticMediaWiki/src/Setup.php(152): SMW\Setup->registerHooks(array)
#8 /var/www/html/extensions/SemanticMediaWiki/includes/SemanticMediaWiki.php(84): SMW\Setup->init(array, string)
#9 /var/www/html/includes/Setup.php(564): SemanticMediaWiki::onExtensionFunction()
#10 /var/www/html/maintenance/run.php(49): require_once(string)
#11 /var/www/html/maintenance/run(3): require(string)
#12 {main}

What should have happened instead?:

update should run

Software version (skip for WMF-hosted wikis like Wikipedia):
Core and extensions are wmf/1.41.0-wmf.13
Semantic MediaWiki is 4.1.1
Semantic Drilldown is master

Other information (browser name/version, screenshots, etc.):

Can be related to [T339834](https://phabricator.wikimedia.org/T339834)

**Comment by physikerwelt** [comment]
This is resolved with the most recent version.
